### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by NetHeritage** [caddy-dns/cloudflare#15]
In caddy 1.x , users can add the "wildcard" subdirective in caddyfile, and caddy will get a wildcard certificate.  This feature is very very helpful if your domain have many subdomains.
Could please add this feature back to caddy2 ?

**Comment by mholt** [comment]
What does this have to do with caddy-dns/cloudflare?

I can't transfer the issue out of the organization, so I will have to close it since I don't see how it's relevant.

**Comment by NetHeritage** [comment]
this is not about caddy-dns/cloudflare, this is about caddy tls directive.  sorry for confusion.
