### ISSUE TITLE
DNS: unrecognized directive in caddyfile

### ISSUE THREAD

**Issue by unixandria-xda** [caddy-dns/cloudflare#16]
When using the example in the readme, caddy crashes with
```
run: adapting config using caddyfile: /etc/caddy/Caddyfile:12: unrecognized directive: dns
```
caddy list-modules show
```
...
dns.providers.cloudflare
...
```

**Comment by mholt** [comment]
What is your full Caddyfile?

**Comment by unixandria-xda** [comment]
https://paste.ubuntu.com/p/MQjSSQKQDF/

**Comment by unixandria-xda** [comment]
https://paste.ubuntu.com/p/cSV3cz7DFT/

**Comment by mholt** [comment]
Ah, your Caddyfile is malformed. Please take the [Caddyfile tutorial](https://caddyserver.com/docs/caddyfile-tutorial) and read about the [Caddyfile structure](https://caddyserver.com/docs/caddyfile/concepts).

In the future, please only open bug reports or feature requests in the issue tracker, usage questions are for our forum: https://caddy.community - thanks!

**Comment by unixandria-xda** [comment]
Would be nice to know what is actually wrong, and no the [REDACTED] parts aren't actually in the file

**Comment by unixandria-xda** [comment]
Especially as _without_ the tls part it works completely fine

**Comment by unixandria-xda** [comment]
According to the docs nothing is wrong, and I literally copied and pasted from the readme minus the API key so if something else is necessary maybe you should mention it

**Comment by unixandria-xda** [comment]
And commenting out the tls { ... } line? Runs fine

So your README obviously forgets to mention some step somewhere

**Comment by mholt** [comment]
@unixandria-xda You didn't follow the instructions:

> then replace the line below with your domain name.

The next line, then, is:

> tls {

Is `tls` your domain name?
