### ISSUE TITLE
Applicable to internal sites?

### ISSUE THREAD

**Issue by kaihendry** [caddy-dns/cloudflare#22]
Is this approach suitable for internal/intranet sites?

I set an example: internal.dabase.com to my machine's IP address 192.168.1.19 and it failed with **No valid IP addresses**

https://s.natalian.org/2021-03-26/no-valid-ip-address.mp4

**Comment by chanux** [comment]
Looks like caddy needs to be able to set a TXT record using the DNS service API (As suggested by [this section](https://github.com/caddyserver/caddy/blob/master/modules/caddytls/automation.go#L332) of code).

**Comment by kaihendry** [comment]
Is it a permission problem? Since my Cloudflare token has **DNS:Edit** permissions for the Zone / domain I am testing with.

**Comment by chanux** [comment]
I can't really see dns-01 challenge happening in your log. Can you find anything about DNS challenge in the logs?

**Comment by kaihendry** [comment]
https://s.natalian.org/2021-03-26/dns.txt

oh... my config is wrong..... my tls email was breaking it! https://s.natalian.org/2021-03-26/dns-working.txt

```
(ins)[hendry@t14s ~]$ curl -i https://internal.dabase.com/
HTTP/2 200
server: Caddy
content-length: 0
date: Fri, 26 Mar 2021 08:57:58 GMT
```

**Comment by kaihendry** [comment]
I created a video about this process btw https://youtu.be/GqZ7yPzWTaQ
