### ISSUE TITLE
Example of docker execution

### ISSUE THREAD

**Issue by tomaswarynyca** [caddy-dns/cloudflare#24]
Could you provide a docker-compose to use caddy and cloudflare?

**Comment by MostHated** [comment]
I second this request.

**Comment by francislavoie** [comment]
See the docs on https://hub.docker.com/_/caddy, it should cover everything you need to know.

```
FROM caddy:<version>-builder AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare

FROM caddy:<version>

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

**Comment by MostHated** [comment]
Thank you for that info, I had not seen it on Caddys site or anywhere else prior.

I did attempt this, but am getting the following "Invalid request headers" error: 

```sh
"tls.obtain","msg":"will retry","error":"[<mysite.com>] Obtain: [<mysite.com>] solving challenges: presenting for challenge: adding temporary record for zone <mysite.com>.: got error status: HTTP 400: [{Code:6003 Message:Invalid request headers}] 
```
Is that something with the plugin, or did I probably do something incorrectly?

**Comment by polarathene** [comment]
> Is that something with the plugin, or did I probably do something incorrectly?

For me, I had accidentally run Caddy without providing my CF API token via ENV var which the Caddyfile config expected.

That resulted in Cloudflare error to Caddy "Invalid request headers". Correctly setting the ENV so Caddy had an actual value to use resolved it :)
