### ISSUE TITLE
dns-01 challenge timed out

### ISSUE THREAD

**Issue by stevetz** [caddy-dns/cloudflare#30]
Similar to issues #28  #13 I am recently having issues renewing the caddy certs, but their fixes aren't working for me.

```
08:40:01 : {"level":"info","ts":1630917601.1305175,"logger":"tls.issuance.acme.acme_client","msg":"trying to solve challenge","identifier":"URL.TLD","challenge_type":"dns-01","ca":"https://acme-v02.api.letsencrypt.org/directory"}
08:42:17 : {"level":"info","ts":1630917737.0010695,"logger":"tls.issuance.acme","msg":"waiting on internal rate limiter","identifiers":["URL.TLD"]}
08:42:17 : {"level":"info","ts":1630917737.0015578,"logger":"tls.issuance.acme","msg":"done waiting on internal rate limiter","identifiers":["URL.TLD"]}
08:42:19 : {"level":"info","ts":1630917739.3439322,"logger":"tls.issuance.acme.acme_client","msg":"trying to solve challenge","identifier":"URL.TLD","challenge_type":"dns-01","ca":"https://acme.zerossl.com/v2/DV90"}
08:44:22 : {"level":"error","ts":1630917862.571245,"logger":"tls.renew","msg":"will retry","error":"[URL.TLD] Renew: [URL.TLD] solving challenges: waiting for solver certmagic.solverWrapper to be ready: timed out waiting for record to fully propagate; verify DNS provider configuration is correct - last error: <nil> (order=https://acme.zerossl.com/v2/DV90/order/y3th-e4qmVaHYssEQcd6VA) (ca=https://acme.zerossl.com/v2/DV90)","attempt":1,"retrying_in":60,"elapsed":262.837809012,"max_duration":2592000}
```

I tried adding `resolvers` to my Caddyfile but see nothing new in the log. There is a txt acme challenge added to cloudflare so the API interaction seems to be OK...

Here's the Caddyfile, nothing I can see to be going wrong:
```
URL.TLD {
        tls {
                dns cloudflare <API_KEY>
        }
}
```

This setup used to work fine, I set it up about 6 months ago, and only now has it started causing issues (so I'm guessing the 90 day cert renewal must have worked OK at least once after setup). Only changes could be from a usual apt update of the LXC caddy is running in. I've not tried downgrading caddy/cloudflare package.

Thanks

**Comment by mholt** [comment]
The error message suggests an external change like something to do with the network or resolver configuration; I would look into that.
