### ISSUE TITLE
[Newbie] What's the need of Cloudflare Dns

### ISSUE THREAD

**Issue by ajhorvath20** [caddy-dns/cloudflare#33]
Hi, I'm new to caddy and I'm trying to understand why do I need to cloudflare dns as I can access all my services via subdomain and I just forwarded 80 and 443 ports on my router. So what's the need for this module? 

My domain is from cloudflare and I also added my dns records. I'm also using cloudflareddns to keep my ip address upto date.

Could you please help me out because I'm not sure what I'm missing.

Thank you

**Comment by mholt** [comment]
Welcome - this module is primarily for solving the DNS challenge of the ACME protocol: https://caddyserver.com/docs/automatic-https#acme-challenges

But it is a general purpose module that can also be used for dynamic DNS, for example: https://github.com/mholt/caddy-dynamicdns

**Comment by ajhorvath20** [comment]
Hi thank you so much for quick response.

I try to add the tls lines in my caddy file but I got error message that tls format is not correct. I will login to my PC first thing in the morning and post you the error if that helps.

Thank you
