### ISSUE TITLE
Can you use this to create non-proxied DNS entries?

### ISSUE THREAD

**Issue by jakubgs** [caddy-dns/cloudflare#36]
The docs for this module are very scarce. My understanding is that this is used to create the TXT record that help create the LetsEncrypt certificates by validating ownership of a domain. Correct?

Could this module be used to create non-proxied CloudFlare DNS records for a setup that uses a [custom certificate and key](https://caddyserver.com/docs/caddyfile/directives/tls#examples)?

**Comment by mholt** [comment]
Do you mean "gray cloud" DNS records? I don't think it matters. It just sets a particular TXT record for ACME challenges only.

(Closing, hopefully that answered your question? Let me know if there's something missing though.)
