### ISSUE TITLE
caddy-dns / cloudflare is broken will not install

### ISSUE THREAD

**Issue by KnucklesNuclear2** [caddy-dns/cloudflare#37]
Hello;
Very new to github Have been trying to install Caddy multiple times. Believe the go.mod and go.sum have broken links in them. That is what is making the install fail. Thanks for your time. And have a great day.

**Comment by azoller1** [comment]
I have built fine using "xcaddy --with github.com/caddy-dns/cloudflare"

Maybe old go version?

**Comment by ItzDabbzz** [comment]
I can't seem to build it either, ive tried the latest version of 2.4.6, and tried [2.4.0](https://i.imgur.com/BQEbUrZ.png)
for some reason i only get here. 
![image](https://user-images.githubusercontent.com/45545996/162615127-a7bca7c6-ce02-4e11-b9bc-d4d1de83dd2d.png)

Heres my current Dockerfile i use to build it.
![image](https://user-images.githubusercontent.com/45545996/162615191-f0395f4d-9975-4468-83d7-7157e3ac2615.png)

**Comment by azoller1** [comment]
You need your token.

acme_dns cloudflare "token here no quotes"

Also, I read somewhere using the cloudflare dns challenge globally with the acme_dns may not work. Instead, use the tls option under each site/domain.

**Comment by ItzDabbzz** [comment]
I think the issue was, i was on go 1.16, after i updated it showed up in the modules list.

**Comment by mholt** [comment]
It was working for me, but I did just upgrade the dependencies anyway.

**Comment by Jimbolino** [comment]
> but I did just upgrade the dependencies anyway

i was researching a bug (possibly with the newest v2.6.4), however when i switch caddy back to v2.6.3 i cannot use this library anymore :)
