### ISSUE TITLE
Deploying a caddy+cloudflare image 

### ISSUE THREAD

**Issue by aTable** [caddy-dns/cloudflare#43]
As mentioned [in issue 24](https://github.com/caddy-dns/cloudflare/issues/24#issuecomment-816782687) it's simple enough to create a custom build of caddy including the cloudflare module. Is there any interest to also ship an official version as part of the range of caddy?

It would be convenient if you only had to do a `docker pull docker.io/caddy:cloudflare`

**Comment by mholt** [comment]
You're welcome to publish such an image, but we are not planning on it.

**Comment by aTable** [comment]
Happy to raise the PR, are you saying it wont happen in this repo and to do it in my own?

**Comment by mholt** [comment]
Yep. There are too many DNS providers and it doesn't make much sense for us to try to officially favor one (or especially all of them equally) and publish singular images with just that plugin.

**Comment by aTable** [comment]
for any future readers: I have [forked this repo](https://github.com/aTable/cloudflare) to deploy an image for convenience. I have only briefly tested so far but its working fine for wildcard certs. To use:

Example `Caddyfile` thanks to [reinhardt](https://reinhardt.dev/posts/caddy-server-wildcards/)

```
{
    debug
    email {env.CLOUDFLARE_EMAIL}
}

*.mydomain.com
 {
    tls {
        dns cloudflare {env.CLOUDFLARE_API_TOKEN}
    }  
    @home host home.mydomain.com
	handle @home {
		root * /sites/home_site
                file_server
	}
     @jellyfin host jellyfin.mydomain.com
	handle @jellyfin {
	      reverse_proxy jellyfin:8096 
	}
}
```

Sample run command  `docker run --name caddy --volume /path/to/Caddyfile:/etc/Caddy/Caddyfile -e CLOUDFLARE_EMAIL='youremail@example.com' -e CLOUDFLARE_API_TOKEN='your_api_token_with_correct_zone_and_dns_permissions' ghcr.io/atable/cloudflare:master`
