### ISSUE TITLE
Issue with resolvers

### ISSUE THREAD

**Issue by MisterDuval** [caddy-dns/cloudflare#50]
Hi,
I'm having issue with resolvers, my caddyFile looks like:

```
[...]
tls {
   dns cloudflare MY_API_KEY
   resolvers 1.1.1.1
}
```

But I'm getting this error because IT blocks DNS requests except from 1.1.1.1.
"error": "[URL] solving challenges: waiting for solver certmagic.solverWrapper to be ready: checking DNS propagation of \"_acme-challenge.URL\": dial tcp **108.162.195.175**:53: i/o timeout

**Comment by mholt** [comment]
Hi,

Please verify you are actually running that config (maybe put some gibberish in it and make sure there's an error when you try to run it, etc) -- and then if there's still a problem, open an issue at https://github.com/caddyserver/certmagic, as this is actually unrelated to Cloudflare.
