### ISSUE TITLE
unrecognized directive: dns

### ISSUE THREAD

**Issue by houmie** [caddy-dns/cloudflare#51]
Hello,

I'm getting this error:

```Error: adapting config using caddyfile: /etc/caddy/Caddyfile:24: unrecognized directive: dns```

Caddyfile:
```
{
    log {
        output file /var/log/caddy/caddy.log {
            roll_size 1gb
            roll_keep 5
            roll_keep_for 720h
        }
    }
    servers 127.0.0.1:5001 {
        listener_wrappers {
            proxy_protocol
        }
        protocols h2c h1
    }
}

:5001 {
    root * /srv/http/default
    file_server
    bind 127.0.0.1
}

tls {
       dns cloudflare {env.CLOUDFLARE_AUTH_TOKEN}
       resolvers 1.1.1.1
}


:80 {
    redir https://{host}{uri} permanent
}
```

How comes it doesn't recognise it?

Thank you

**Comment by misaert** [comment]
Hi @houmie,

Maybe with `CLOUDFLARE_API_KEY` instead of `CLOUDFLARE_AUTH_TOKEN`?

**Comment by mholt** [comment]
Your Caddyfile is malformed; `tls` is being treated as a domain name, and `dns` is being treated as a directive, but actually `tls` is probably intended to be a _directive_, and `dns` is its subdirective.

See: https://caddyserver.com/docs/caddyfile/concepts#structure

@misaert Thanks for chiming in! :)

**Comment by houmie** [comment]
HI @misaert 

Sorry, I have named them badly. But I am using the API key.

echo "export CLOUDFLARE_AUTH_TOKEN=12345xxxx" >> ~/.bashrc
source ~/.bashrc

```
tls {
       dns cloudflare {env.CLOUDFLARE_AUTH_TOKEN}
       resolvers 1.1.1.1
}
```
