### ISSUE TITLE
Split DNS issue

### ISSUE THREAD

**Issue by fzaffa** [caddy-dns/cloudflare#53]
Hello,

i am having issues obtaning certs with DNS challenge (only with Caddy, not with certbot) due to a split horizon dns config.

the subdomain `int.mydomain.com` is resolved locally, and on the local dns server config (unbound) there is an override to resolve the `*.int.mydomain.com` locally (needed to allow not only local machines but also machines connected with a VPN to resolve local domains).

If I try to obtain a certificate using the cloudflare dns challenge for a domain that is `service.int.mydomain.com` I get this error
` solving challenges: presenting for challenge: could not determine zone for domain`.

If I remove the local override in unbound everything works perfectly but I can't really do that or I'd break the dns resolving for remote machines.

Just to add, certbot works even with the local dns override.

**Comment by mholt** [comment]
You can configure which resolvers to use when conducting the DNS challenge: https://caddyserver.com/docs/caddyfile/directives/tls#resolvers :+1:

(In the future, please ask usage-related questions in our forum: https://caddy.community - thanks!)
