### ISSUE TITLE
Missing API token results in unintuitve error message

### ISSUE THREAD

**Issue by tombh** [caddy-dns/cloudflare#72]
For some reason my Caddy wasn't picking up ENV variables. So when the DNS challenge was made I got this error message: `solving challenges: presenting for challenge: adding temporary record for zone \"mydomain.com.\": got error status: HTTP 400: [{Code:6003 Message:Invalid request headers}]`. At first that made me think that Cloudflare's API had been updated to require a different header or something. But in fact it was just that it was probably sending an empty API token.

It's not a big deal, happy to see this closed immediately. The main thing is that the error message is searchable, and might save somebody 5 minutes of head scratching.

**Comment by tombh** [comment]
Duplicate of #27

**Comment by mholt** [comment]
Thanks; maybe we should add this to the README :upside_down_face: Since Cloudflare hasn't improved the error message.

**Comment by Breinich** [comment]
if `caddy environ` echoes correctly my api token, can the problem be that caddy sends empty api token?

**Comment by Breinich** [comment]
It is, I suppose, you can see it here: https://caddy.community/u/breinich/notifications
