### ISSUE TITLE
build --with github.com/caddy-dns/cloudflare still only builds with v2.7.6

### ISSUE THREAD

**Issue by wazerstar** [caddy-dns/cloudflare#76]
Will this be fixed in the near future ?

I made this [ticket](https://github.com/caddy-dns/cloudflare/issues/69) some time ago and its closed because it fixed fatal error in building but its still locked to only build up to caddy v2.7.6

Using

`xcaddy build master --with github.com/caddy-dns/cloudflare@master=github.com/mohammed90/cloudflare@master`

Allows building latest caddy, but that was just a bandaid at that time, what is the future looking like for this plugin.

**Comment by mholt** [comment]
I believe it won't be an issue once 2.8 is released, if I understand it correctly.

**Comment by wazerstar** [comment]
> I believe it won't be an issue once 2.8 is released, if I understand it correctly.

So that would also work with all nightlies/beta's and not only when we hit 2.8 final release?

**Comment by mholt** [comment]
What would also work?

**Comment by wazerstar** [comment]
> What would also work?

I mean you believe it will work for when 2.8 is released, but what with all small/beta/nightly releases after 2.8, 

would xcaddy build master --with github.com/caddy-dns/cloudflare work with all small changes after that or would it only be after each milestone as caddy final releases?

**Comment by mholt** [comment]
My understanding is that the current issues are caused because Go doesn't see that 2.7.6 is a "child" of 2.7, because it was tagged from a separate branch other than master. But 2.8 will be tagged from master again, so I think everything should just work as expected then.

**Comment by mholt** [comment]
Should be fixed now with the release of 2.8
