### ISSUE TITLE
Certificate renewal stopped working

### ISSUE THREAD

**Issue by himazawa** [caddy-dns/cloudflare#81]
I'm using caddy in Docker with the following dockerfile:

```
FROM caddy:2-builder AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare \
    --with github.com/dulli/caddy-wol

FROM caddy:2

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

and the following caddyfile:
```
{
  log
  ocsp_stapling off
}

...
ag.prismlab.cc {
  tls {
    dns cloudflare {env.CF_API_TOKEN}
    resolvers 1.1.1.1
  }
  reverse_proxy 192.168.1.254:8081
}

...
```

Starting yesterday I'm getting [errors](https://gist.github.com/himazawa/0f5f9698a32d0549a898f33abd7c2c4b) at caddy startup.

The CF token is correctly set to `Zone.Zone:Read` and `Zone.DNS:Edit`.

I already tried to rotate the token (just in case) and re-built Caddy without any improvement. 

The docker container is using `1.1.1.1` as DNS.

It was working correctly in the past, no idea what changed that could have break it.

**Comment by recon2710** [comment]
Second this I have something very similar. I am not using docker to run Caddy. Cloudflare is setup correctly, I see the TXT challenges being added to DNS, however it errors out at propagation. I saw the note to add resolvers ie 1.1.1.1 , that did nothing. Not sure what it could be as everything was working fine up until today

**Comment by mholt** [comment]
It seems reddit.prismlab.cc has no DNS records:

```
$ doggo --any reddit.prismlab.cc
NAME	TYPE	CLASS	TTL	ADDRESS	NAMESERVER 

```
