### ISSUE TITLE
What is the correct syntax of using it?

### ISSUE THREAD

**Issue by skrlance** [caddy-dns/cloudflare#88]
Hi, I see that you have mentioned the syntax to add in the Caddyfile:

```
tls {
  dns cloudflare {env.CF_API_TOKEN}
}

```
But, I am very much confused by {env.CF_API_TOKEN}! 

Lets suppose the following is my Cloudflare API token:

`1OqES9+C@ePud@h@DrE!`

So, the syntax on Caddyfile will be which of the following:

1.
```
tls {
  dns cloudflare {env.1OqES9+C@ePud@h@DrE!}
}
```

2.
```
tls {
  dns cloudflare env.1OqES9+C@ePud@h@DrE!
}
```

3.
```
tls {
  dns cloudflare 1OqES9+C@ePud@h@DrE!
}
```

4.
```
tls {
  dns cloudflare {1OqES9+C@ePud@h@DrE!}
}
```
I am asking it because I am not a programmer or expert in these, but I can use it if I know the correct syntax. So, please consider helping me by telling which among 1,2,3 and 4 is the correct syntax to keep in the Caddyfile?

**Comment by mholt** [comment]
That's a placeholder: https://caddyserver.com/docs/conventions#placeholders

Use it literally if you have an envrionment variable set that contains your API token. It's usually a better idea than storing credentials in your config.

**Comment by skrlance** [comment]
Thank you matt! I also got to know the resolution asking the same question to the AI. Also, I wanna help for someone who is dealing with same type of issue. Here is the solution:

First we need to add CloudFlare API Token to the environment typing the following command directly on SSH:

`export CF_API_TOKEN=f4HwB6v0X4fc7E3_1OF0nrqeVbN2-Rb-OpGxffYG`

Or, permanent method:

`nano /etc/environment`

Then add:

`CF_API_TOKEN=1OqES9+C@ePud@h@DrE!`

Save and Exit

Where 1OqES9+C@ePud@h@DrE! will be your CloudFlare generated API token.

Save and exit:
After that add the syntax on Caddyfile:

```
	tls {
		dns cloudflare {env.CF_API_TOKEN}
	}
```
